language: android
android:
  components:
  - tools
  - build-tools-23.0.3
  - extra-android-m2repository
  - android-23
before_install:
- chmod +x .buildscript/deploy_snapshot.sh
jdk:
- oraclejdk8
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: required
script: "./gradlew build --stacktrace"
after_success:
- ".buildscript/deploy_snapshot.sh"
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: FehqhSPXt97mROyTiWiSRs+0JCgTUrYJ0p2kA6ESJbjV37OxtM+/ycWogHyJ1kgwB6wbBzcC/rBSIDi9Zh+eJ1KAiosFKVWj8sD7vozfnTepReuxG6q+Fd6qm9k2FLAzE5p8N5+dwel52con7j2q9L3cMtr6yC4Tud1I8vvQuSaYA0Jr3QqKwT0bkvU0EcxM5dCZ3Ri7CmQJ0p9Er9KWAvJZB6dzwljOsiMPxK2yxQii4wbtLOjgbuzE+R7yMkPq3CN25xvfOf5TWTqBeTCjEpdzub3rG3JQDuZb7+wmY+8ei+pWCWZPCX+9d88A/rXmKUzgaYs3+QuGibJ4r9u/Zwfy02dJ2x9BAZgaeum6KP581lfXn325HAQIpIAGXkHh5AE1PfVMhdP7nQrgp0x/D2MPltgJtswtiTJcCKWS0W2X+HkWMhadUpOPhBUIFkik5Ugo6AlIbcgy1I3T00wrNOs8ffMzcf1LpE2sBuNfkL6SDrYkKVwPVDqZFRv5aaTfPuG36cuiCg833MPZ7I1ge0CkJxq7UFogj/9FsVjpWsxjqUIOvbzMAFLqrcYEPc3GEj5pOS2rn5XeuhmsVlJ/Ma/sMynGBaiBchFwpTY/CZrNuxkasmERtQje0N2ghlghUbQuXogwaBz9S3IRX2bXP2Vft3Q7Mi3S7zgcN84wygw=
  - secure: UUDI2Cq2Y4/BphpJGSaQGv1DB3t7tukv4dsd01/ICcfTA5LAlgfFlESBYU3clG8Nh8AguHOZXWElLo8FO0l1A3qNzViCAZXgTfn4EqmNO36MuWg4ygfPmcwCzXijDRKirrv1yqZhbMSPUyRgCjKsHzVz+ZSrqOnIJ/iI1hXeq+aAtRIw1SXiTtkPxQe0LoxiPXPmmCtlzEBw41dydOIKCZMgz8+tpB0QV0SDANO9MNjPfjk5X+E23ta7iYm+dOBknGRogVMTuXcoQKeGGpoPyrLbnRCOfQFv0B+Z90JswUb17ip3hrXb3tjkM4XU5X2gQDJ25CNwWH2buJifA6dfkeHGnfzfQtGaNAP6keOs4ETKIJwXkvByuOXcyak/WpX66CtqJh3BeOjm2y1x/oSszI5YRvZdNCBkHNXfCjLOx2+wnExUQHL6XHPdwaTDmvVreRM6z64wcmvhNfy4H9oOrRyalCnoa19vY5PLUKCnmbRYCY2EATBt9BGdiZ5LFC+FA9Vh9eB6nVKBqHzoDxpihLZDT+aiw8n6cubwI/4k8hwqwL9vS1KoS0hYK3rkUQ044Feo1hlq+XiV4MrfV0q/VAasQ0lRkAbynXLySSjnvRSYw0qSvufne3OnmsSibg5EzIcM7BveUXUHADRcOeRzH6Hx0flRgXFyiBP9JOXbMeA=
